export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";

//for current product

export const CURRENT_PRODUCT_LOADING = "CURRENT_PRODUCT_LOADING";
export const CURRENT_PRODUCT_ERROR = "CURRENT_PRODUCT_ERROR";
export const CURRENT_PRODUCT_SUCCESS = "CURRENT_PRODUCT_SUCCESS";
